import { ProjectType } from "../components/AdminPage/Project/AdminTypes.ts";

export const PROJECT_EXAMPLE_DATA: ProjectType[] = [
  {
    id: 1,
    name: "First Project",
    security: "PUBLIC",
    disabled: false,
    stages: {
      stage1: "Proto",
      stage2: "SP1",
      stage3: "SP2",
      stage4: "LP1",
      stage5: "LP2",
      stage6: "M",
      active: "LP1",
    },
    colors: [
      {
        name: "White",
        color: "#ffffff",
        text: "black",
        id: 1,
      },
      {
        name: "Black",
        color: "#252329",
        text: "white",
        id: 2,
      },
      {
        name: "Red",
        color: "#ed3a3a",
        text: "white",
        id: 3,
      },
      {
        name: "Dark red",
        color: "#771d1d",
        text: "white",
        id: 4,
      },
      {
        name: "Gray",
        color: "#737373",
        text: "white",
        id: 5,
      },
    ],
  },
  {
    id: 2,
    name: "Second test project",
    security: "PUBLIC",
    disabled: false,
    stages: {
      stage1: "Proto",
      stage2: "SP1",
      stage3: "SP2",
      stage4: "LP1",
      stage5: "LP2",
      stage6: "M",
      active: "LP1",
    },
    colors: [
      {
        name: "White",
        color: "#ffffff",
        text: "black",
        id: 6,
      },
      {
        name: "Black",
        color: "#252329",
        text: "white",
        id: 7,
      },
      {
        name: "Red",
        color: "#ed3a3a",
        text: "white",
        id: 8,
      },
      {
        name: "Dark red",
        color: "#771d1d",
        text: "white",
        id: 9,
      },
      {
        name: "Gray",
        color: "#737373",
        text: "white",
        id: 10,
      },
    ],
  },
  {
    id: 3,
    name: "And one last test project",
    security: "PUBLIC",
    disabled: false,
    stages: {
      stage1: "Proto",
      stage2: "SP1",
      stage3: "SP2",
      stage4: "LP1",
      stage5: "LP2",
      stage6: "M",
      active: "LP1",
    },
    colors: [
      {
        name: "White",
        color: "#ffffff",
        text: "black",
        id: 11,
      },
      {
        name: "Black",
        color: "#252329",
        text: "white",
        id: 12,
      },
      {
        name: "Red",
        color: "#ed3a3a",
        text: "white",
        id: 13,
      },
      {
        name: "Dark red",
        color: "#771d1d",
        text: "white",
        id: 14,
      },
      {
        name: "Gray",
        color: "#737373",
        text: "white",
        id: 15,
      },
    ],
  },
];
