import {
  ActionFormatTypes,
  ProjectType,
} from "../components/AdminPage/Project/AdminTypes.ts";

export const PROJECT_EXAMPLE_DATA: ProjectType[] = [
  {
    id: 1,
    name: "First Project",
    security: "PUBLIC",
    disabled: false,
    stages: {
      stage1: "Proto",
      stage2: "SP1",
      stage3: "SP2",
      stage4: "LP1",
      stage5: "LP2",
      stage6: "M",
      active: "LP1",
    },
    colors: [
      {
        name: "White",
        color: "#ffffff",
        text: "black",
        id: 1,
      },
      {
        name: "Black",
        color: "#252329",
        text: "white",
        id: 2,
      },
      {
        name: "Red",
        color: "#ed3a3a",
        text: "white",
        id: 3,
      },
      {
        name: "Dark red",
        color: "#771d1d",
        text: "white",
        id: 4,
      },
      {
        name: "Gray",
        color: "#737373",
        text: "white",
        id: 5,
      },
    ],
    actions: [
      {
        actionId: 1,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 2,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 2, actionName: "Tryout" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 3,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 3, actionName: "EO plan" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 4,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 4, actionName: "EO issued" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 5,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 5, actionName: "W&S (keep)" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 6,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 7,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 8,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 2, actionName: "Tryout" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 9,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 5, actionName: "W&S (keep)" },
        status: { statusId: 1, statusName: "Open" },
        plan: true,
      },
      {
        actionId: 10,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 6, actionName: "C/M" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 11,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 12,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 13,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 2, actionName: "Tryout" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 14,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 3, actionName: "EO plan" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 15,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 4, actionName: "EO issued" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 16,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 5, actionName: "W&S (keep)" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 17,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 6, actionName: "C/M" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 18,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 19,
        selectedClass: { classId: 4, className: "Equipment" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 20,
        selectedClass: { classId: 4, className: "Equipment" },
        action: { actionId: 6, actionName: "C/M" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 21,
        selectedClass: { classId: 4, className: "Equipment" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
    ],
  },
  {
    id: 2,
    name: "Second test project",
    security: "PUBLIC",
    disabled: false,
    stages: {
      stage1: "Proto",
      stage2: "SP1",
      stage3: "SP2",
      stage4: "LP1",
      stage5: "LP2",
      stage6: "M",
      active: "LP1",
    },
    colors: [
      {
        name: "White",
        color: "#ffffff",
        text: "black",
        id: 6,
      },
      {
        name: "Black",
        color: "#252329",
        text: "white",
        id: 7,
      },
      {
        name: "Red",
        color: "#ed3a3a",
        text: "white",
        id: 8,
      },
      {
        name: "Dark red",
        color: "#771d1d",
        text: "white",
        id: 9,
      },
      {
        name: "Gray",
        color: "#737373",
        text: "white",
        id: 10,
      },
    ],
    actions: [
      {
        actionId: 22,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 23,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 2, actionName: "Tryout" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 24,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 3, actionName: "EO plan" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 25,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 4, actionName: "EO issued" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 26,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 5, actionName: "W&S (keep)" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 27,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 28,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 29,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 2, actionName: "Tryout" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 30,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 5, actionName: "W&S (keep)" },
        status: { statusId: 1, statusName: "Open" },
        plan: true,
      },
      {
        actionId: 31,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 6, actionName: "C/M" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 32,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 33,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 34,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 2, actionName: "Tryout" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 35,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 3, actionName: "EO plan" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 36,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 4, actionName: "EO issued" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 37,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 5, actionName: "W&S (keep)" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 38,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 6, actionName: "C/M" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 39,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 40,
        selectedClass: { classId: 4, className: "Equipment" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 41,
        selectedClass: { classId: 4, className: "Equipment" },
        action: { actionId: 6, actionName: "C/M" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 42,
        selectedClass: { classId: 4, className: "Equipment" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
    ],
  },
  {
    id: 3,
    name: "And one last test project",
    security: "PUBLIC",
    disabled: false,
    stages: {
      stage1: "Proto",
      stage2: "SP1",
      stage3: "SP2",
      stage4: "LP1",
      stage5: "LP2",
      stage6: "M",
      active: "LP1",
    },
    colors: [
      {
        name: "White",
        color: "#ffffff",
        text: "black",
        id: 11,
      },
      {
        name: "Black",
        color: "#252329",
        text: "white",
        id: 12,
      },
      {
        name: "Red",
        color: "#ed3a3a",
        text: "white",
        id: 13,
      },
      {
        name: "Dark red",
        color: "#771d1d",
        text: "white",
        id: 14,
      },
      {
        name: "Gray",
        color: "#737373",
        text: "white",
        id: 15,
      },
    ],
    actions: [
      {
        actionId: 43,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 44,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 2, actionName: "Tryout" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 45,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 3, actionName: "EO plan" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 46,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 4, actionName: "EO issued" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 47,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 5, actionName: "W&S (keep)" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 48,
        selectedClass: { classId: 1, className: "Design" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 49,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 50,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 2, actionName: "Tryout" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 51,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 5, actionName: "W&S (keep)" },
        status: { statusId: 1, statusName: "Open" },
        plan: true,
      },
      {
        actionId: 52,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 6, actionName: "C/M" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 53,
        selectedClass: { classId: 2, className: "Part" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 54,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 55,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 2, actionName: "Tryout" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 56,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 3, actionName: "EO plan" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 57,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 4, actionName: "EO issued" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 58,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 5, actionName: "W&S (keep)" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 59,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 6, actionName: "C/M" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 60,
        selectedClass: { classId: 3, className: "Workability" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
      {
        actionId: 61,
        selectedClass: { classId: 4, className: "Equipment" },
        action: { actionId: 1, actionName: "U/Consideration" },
        status: { statusId: 1, statusName: "Open" },
        plan: false,
      },
      {
        actionId: 62,
        selectedClass: { classId: 4, className: "Equipment" },
        action: { actionId: 6, actionName: "C/M" },
        status: { statusId: 2, statusName: "CM" },
        plan: true,
      },
      {
        actionId: 63,
        selectedClass: { classId: 4, className: "Equipment" },
        action: { actionId: 7, actionName: "Improved" },
        status: { statusId: 3, statusName: "Closed" },
        plan: true,
      },
    ],
  },
];

export const ACTION_FORMAT_DEFAULT: ActionFormatTypes = {
  classes: [
    { classId: 1, className: "Design" },
    { classId: 2, className: "Part" },
    { classId: 3, className: "Workability" },
    { classId: 4, className: "Equipment" },
  ],
  actions: [
    { actionId: 1, actionName: "U/Consideration" },
    { actionId: 2, actionName: "Tryout" },
    { actionId: 3, actionName: "EO plan" },
    { actionId: 4, actionName: "EO issued" },
    { actionId: 5, actionName: "W&S (keep)" },
    { actionId: 6, actionName: "C/M" },
    { actionId: 7, actionName: "Improved" },
  ],
  status: [
    { statusId: 1, statusName: "Open" },
    { statusId: 2, statusName: "CM" },
    { statusId: 3, statusName: "Closed" },
  ],
};
